# Generated by Django 3.1.2 on 2020-10-31 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_device_user'),
        ('users', '0002_profile_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='device',
            field=models.OneToOneField(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.PROTECT, to='device.device'),
        ),
    ]
