# Generated by Django 3.1.2 on 2020-11-02 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201031_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='device',
        ),
    ]
