# Generated by Django 3.1.2 on 2020-11-02 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('Doorbell', 'Doorbell'), ('Lock', 'Locked'), ('Unlock', 'Unlocked')], default='Doorbell', max_length=10)),
            ],
        ),
    ]
