# Generated by Django 3.1.2 on 2020-11-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20201102_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='event',
            name='device_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(max_length=10),
        ),
    ]
