# Generated by Django 3.1.2 on 2020-10-31 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_nickname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
