# Generated by Django 3.1.2 on 2020-11-23 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_device_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='device_id',
        ),
    ]
