# Generated by Django 3.1.2 on 2020-12-03 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_remove_device_device_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='user',
        ),
    ]
