# Generated by Django 2.2 on 2020-08-10 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200723_1635'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
